### ISSUE TITLE
Rules triggered for conditional blocks

### ISSUE THREAD

**Issue by An-dz** [jsfehler/flake8-multiline-containers#14]
Version 0.0.7 is checking the rules for the conditional block parenthesis:

```python
if (False
   or True):
    "a"
```

The above will trigger both rules, but that's not a container.

**Comment by jsfehler** [comment]
@An-dz This is partially the result of checking tuples at all. Unlike lists or sets, tuples are more tricky to detect. Take the following example:

Not a tuple:
```
x = (500 > 1200)
 > True
```

Yep, it's a tuple:
```
x = (500 > 1200,)
> (True,)
```

In a conditional statement, you could use a list or set. Lunula brackets are the only situation where a container is not formed unless a comma is used.

I don't think there's an elegant situation for detecting the difference between a tuple and not a tuple 100% of the time.

An alternate approach would be adding a separate rule for checking conditional blocks and ignoring them entirely in 101 and 102.

**Comment by An-dz** [comment]
Well, a tuple must have a comma to be one, except if it's empty or you're using the `tuple` built-in with an `iterable` variable, but in those two cases you're not making it multiline.

```python
# So these are tuples:
( 1, )
( 1, 2, 3, 4 )

# These are tuples that require no checking
()
tuple(y)

# These are not tuples:
x = ( 150 > y )
x = 150 if ( y > z ) else 0
if ( x or y ):

# Here's a mix of them:
x = ( y, z ) if ( y > z ) else ( y, )
#   ^tuple      ^nope          ^tuple
```

These have commas and are not tuples but can be recognised apart by checking it has a word character before it:
(regex `[a-zA-Z0-9_]\s*`) (But Python 3 added more allowed characters [\[1\]](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier)):
```python
def ex( x, y ):
ex( x, y )
range( 0, 100, 2 )
```

**Comment by An-dz** [comment]
While trying to fix this myself I noticed that this regexp can be optimised:
https://github.com/jsfehler/flake8-multiline-containers/blob/272d25233b5a92046beeffc76ba084dd7bf9d62d/flake8_multiline_containers.py#L15

This is more than sufficient and will have the same effect:
```python
FUNCTION_CALL_REGEX = r'\w\('
```

Yet both still trigger a false positive:
```python
def function (a,
              b):
    pass

**Comment by jsfehler** [comment]
@An-dz I've fixed this, somewhat, on the master branch. Conditional blocks should now be ignored, along with function calls with strange whitespace.

I still don't think there's a perfect solution. However, stuff like `x = ( 150 > y )` seems very unlikely to be multiline, so if it's detected as a single line tuple, I can live with that.

**Comment by An-dz** [comment]
Awesome, I'll update it on my projects.
